// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWachxmLTjSFsRBEBTXa9Hmeu0G5cKECA',
    appId: '1:1065661038230:web:ab6073e210f68adf020cb7',
    messagingSenderId: '1065661038230',
    projectId: 'pinni-b2a39',
    authDomain: 'pinni-b2a39.firebaseapp.com',
    storageBucket: 'pinni-b2a39.appspot.com',
    measurementId: 'G-HC4J9NCE34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXftL7YLFo1ilXy0u4WSpFCvJ9dwwvOwQ',
    appId: '1:1065661038230:android:6b67eda8b95c63a1020cb7',
    messagingSenderId: '1065661038230',
    projectId: 'pinni-b2a39',
    storageBucket: 'pinni-b2a39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdkDJXtYiBovK7BaSdkfMSG3oHgJmEhy0',
    appId: '1:1065661038230:ios:f71c622eaeab4340020cb7',
    messagingSenderId: '1065661038230',
    projectId: 'pinni-b2a39',
    storageBucket: 'pinni-b2a39.appspot.com',
    iosBundleId: 'com.example.pinnitagpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdkDJXtYiBovK7BaSdkfMSG3oHgJmEhy0',
    appId: '1:1065661038230:ios:5e65e4444425c970020cb7',
    messagingSenderId: '1065661038230',
    projectId: 'pinni-b2a39',
    storageBucket: 'pinni-b2a39.appspot.com',
    iosBundleId: 'com.example.pinnitagpay.RunnerTests',
  );
}
